# Generated by Django 5.1.3 on 2025-01-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(max_length=200)),
                ('mdp', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Creneau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
            ],
            options={
                'db_table': 'Creneau',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_etudiant', models.CharField(max_length=8, unique=True)),
                ('autorise', models.BooleanField(default=True, null=True)),
                ('date_derniere_reserv', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'Etudiant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_id', models.IntegerField()),
                ('date_field', models.DateField(db_column='date_')),
                ('admin_field', models.BooleanField(db_column='admin_')),
            ],
            options={
                'db_table': 'Reservation',
                'managed': False,
            },
        ),
    ]
