# Generated by Django 5.1.5 on 2025-01-23 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={},
        ),
        migrations.AlterModelOptions(
            name='creneau',
            options={},
        ),
        migrations.AlterModelOptions(
            name='etudiant',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={},
        ),
    ]
